export const HERO_TYPES = {
  knight: {
    name: 'Lady Arwyn',
    title: 'Stalwart Knight',
    skill: {
      title: 'Defensive Stance',
      description:
        'Spend 2 AP to raise your shield, gaining +1 defence until your next turn.',
      cost: 2,
    },
    movement: 3,
    hp: 11,
    maxHp: 11,
    maxAp: 3,
    ap: 3,
    defence: 4,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 1,
    icon: 'K',
    image: '/hero/crusader.png',
    weapons: [
      {
        name: 'Sword',
        attack: 2,
        defence: 0,
        dice: 'strength',
        image: '/sword.svg',
        attackType: 'melee',
      },
      {
        name: 'Shield',
        attack: 1,
        defence: 2,
        dice: 'strength',
        image: '/shield.svg',
        attackType: 'melee',
      },
    ],
  },
  elf: {
    name: 'Selene',
    title: 'Silent Huntress',
    skill: {
      title: 'Forest Stealth',
      description:
        'Spend 2 AP to blend with the woods, ignoring line of sight for movement this turn.',
      cost: 2,
    },
    movement: 4,
    hp: 7,
    maxHp: 7,
    maxAp: 4,
    ap: 4,
    defence: 2,
    strengthDice: 1,
    agilityDice: 3,
    magicDice: 2,
    icon: 'E',
    image: '/elf.png',
    weapons: [
      {
        name: 'Bow',
        attack: 2,
        defence: 0,
        dice: 'agility',
        image: '/bow.svg',
        attackType: 'range',
        range: 3,
      },
      {
        name: 'Dagger',
        attack: 1,
        defence: 1,
        dice: 'agility',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  viking: {
    name: 'Freya',
    title: 'Fierce Shieldmaiden',
    skill: {
      title: 'Berserker Rage',
      description: 'Spend 2 AP to gain +2 attack power in combat.',
      cost: 2,
      bonus: 2,
    },
    movement: 3,
    hp: 9,
    maxHp: 9,
    maxAp: 3,
    ap: 3,
    defence: 3,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 1,
    icon: 'V',
    image: '/hero/freya.png',
    weapons: [
      {
        name: 'Axe',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/weapon/viking-axe.webp',
        attackType: 'melee',
      },
    ],
  },
  sorceress: {
    name: 'Ethairna',
    title: 'Arcane Mistress',
    skill: {
      title: 'Seeking Bolt',
      description:
        'Spend 2 AP then roll magic (5+). On success, deal 1 damage to an enemy within 4 spaces.',
      cost: 2,
    },
    movement: 4,
    hp: 6,
    maxHp: 6,
    maxAp: 6,
    ap: 6,
    defence: 2,
    strengthDice: 1,
    agilityDice: 2,
    magicDice: 3,
    icon: 'S',
    image: '/hero/red-wizard.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  wizard: {
    name: 'Serilda the Blue',
    title: 'Blue Flame Wizard',
    skill: {
      title: 'Magic Arrow',
      description:
        'Spend 2 AP and roll magic (6+). A hit deals 2 damage to a target up to 2 spaces away.',
      cost: 2,
    },
    movement: 3,
    hp: 5,
    maxHp: 5,
    maxAp: 6,
    ap: 6,
    defence: 3,
    strengthDice: 1,
    agilityDice: 2,
    magicDice: 3,
    icon: 'W',
    image: '/hero/blue-wizard.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  barbarian: {
    name: 'Groka Ull',
    title: 'Savage Berserker',
    skill: {
      title: 'Battle Rage',
      description:
        'Spend 2 AP before attacking to gain +2 on that attack roll.',
      cost: 2,
    },
    movement: 3,
    hp: 9,
    maxHp: 9,
    maxAp: 3,
    ap: 3,
    defence: 2,
    strengthDice: 3,
    agilityDice: 2,
    magicDice: 1,
    icon: 'B',
    image: '/hero/barbarian.png',
    weapons: [
      {
        name: 'Axe',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/weapon/viking-axe.webp',
        attackType: 'melee',
      },
    ],
  },
  rogue: {
    name: 'Lunara',
    title: 'Nightblade',
    skill: {
      title: 'Shadow Walk',
      description:
        'Spend 2 AP and roll agility (6+). If successful, move up to your speed ignoring enemies and deal 1 damage where you stop.',
      cost: 2,
    },
    movement: 5,
    hp: 6,
    maxHp: 6,
    maxAp: 4,
    ap: 4,
    defence: 2,
    strengthDice: 2,
    agilityDice: 3,
    magicDice: 1,
    icon: 'R',
    image: '/hero/ninja.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  paladin: {
    name: 'Lady Liora',
    title: 'Battle Veteran',
    skill: {
      title: 'Divine Might',
      description:
        'Spend 2 AP and roll magic (4+). A success adds +2 to your next melee attack.',
      cost: 2,
    },
    movement: 3,
    hp: 9,
    maxHp: 9,
    maxAp: 4,
    ap: 4,
    defence: 4,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 2,
    icon: 'P',
    image: '/hero/magic-knight.png',
    weapons: [
      {
        name: 'Hammer',
        attack: 2,
        defence: 0,
        dice: 'strength',
        image: '/weapon/mjolnir.webp',
        attackType: 'melee',
      },
    ],
  },
  cleric: {
    name: 'Uliessa',
    title: 'Divine Healer',
    skill: {
      title: 'Heal',
      description:
        'Spend 2 AP while casting a spell to restore 4 HP to a hero up to 3 rooms away.',
      cost: 2,
    },
    movement: 4,
    hp: 7,
    maxHp: 7,
    maxAp: 6,
    ap: 6,
    defence: 4,
    strengthDice: 2,
    agilityDice: 1,
    magicDice: 3,
    icon: 'C',
    image: '/hero/priestess-animate.gif',
    weapons: [
      {
        name: 'Hammer',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/weapon/earthshaker.webp',
        attackType: 'melee',
      },
    ],
  },
  ranger: {
    name: 'Wynneth Keleas',
    title: 'Swift Tracker',
    skill: {
      title: 'Stealth',
      description:
        'Spend 2 AP to move through enemies without stopping this turn.',
      cost: 2,
    },
    movement: 4,
    hp: 7,
    maxHp: 7,
    maxAp: 4,
    ap: 4,
    defence: 2,
    strengthDice: 2,
    agilityDice: 3,
    magicDice: 1,
    icon: 'A',
    image: '/hero/dark-elf.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
      {
        name: 'Bow',
        attack: 2,
        defence: 0,
        dice: 'agility',
        image: '/bow.svg',
        attackType: 'range',
        range: 2,
      },
    ],
  },
}

