export const HERO_TYPES = {
  knight: {
    name: 'Lady Arwyn',
    title: 'Stalwart Knight',
    skill: {
      title: 'Defensive Stance',
      description:
        '2 AP: raise shield for +1 defence until next turn.',
      cost: 2,
    },
    skill2: {
      title: 'Hold the Line',
      description: 'Passive: adjacent allies gain +1 defence.',
    },
    quote: 'For honor and the realm!',
    movement: 3,
    hp: 11,
    maxHp: 11,
    maxAp: 3,
    ap: 3,
    defence: 4,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 1,
    icon: 'K',
    image: '/hero/crusader.png',
    weapons: [
      {
        name: 'Sword',
        attack: 2,
        defence: 0,
        dice: 'strength',
        image: '/sword.svg',
        attackType: 'melee',
      },
      {
        name: 'Shield',
        attack: 1,
        defence: 2,
        dice: 'strength',
        image: '/shield.svg',
        attackType: 'melee',
      },
    ],
  },
  elf: {
    name: 'Selene',
    title: 'Silent Huntress',
    skill: {
      title: 'Forest Stealth',
      description:
        '2 AP: blend with woods, ignore line of sight.',
      cost: 2,
    },
    skill2: {
      title: 'Keen Senses',
      description: 'Passive: reveal traps in adjacent rooms.',
    },
    quote: 'Silent as the moonlight.',
    movement: 4,
    hp: 7,
    maxHp: 7,
    maxAp: 4,
    ap: 4,
    defence: 2,
    strengthDice: 1,
    agilityDice: 3,
    magicDice: 2,
    icon: 'E',
    image: '/elf.png',
    weapons: [
      {
        name: 'Bow',
        attack: 2,
        defence: 0,
        dice: 'agility',
        image: '/bow.svg',
        attackType: 'range',
        range: 3,
      },
      {
        name: 'Dagger',
        attack: 1,
        defence: 1,
        dice: 'agility',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  viking: {
    name: 'Freya',
    title: 'Fierce Shieldmaiden',
    skill: {
      title: 'Berserker Rage',
      description: '2 AP: gain +2 attack power this combat.',
      cost: 2,
      bonus: 2,
    },
    skill2: {
      title: 'Iron Resolve',
      description: 'Passive: immune to fear effects.',
    },
    quote: 'Shield first, questions later!',
    movement: 3,
    hp: 9,
    maxHp: 9,
    maxAp: 3,
    ap: 3,
    defence: 3,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 1,
    icon: 'V',
    image: '/hero/freya.png',
    weapons: [
      {
        name: 'Axe',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/weapon/viking-axe.webp',
        attackType: 'melee',
      },
    ],
  },
  sorceress: {
    name: 'Ethairna',
    title: 'Arcane Mistress',
    skill: {
      title: 'Seeking Bolt',
      description:
        '2 AP: magic (5+) to deal 1 damage up to 4 spaces.',
      cost: 2,
    },
    skill2: {
      title: 'Mana Shield',
      description: 'Passive: first damage each turn reduced by 1.',
    },
    quote: 'Power flows through me.',
    movement: 4,
    hp: 6,
    maxHp: 6,
    maxAp: 6,
    ap: 6,
    defence: 2,
    strengthDice: 1,
    agilityDice: 2,
    magicDice: 3,
    icon: 'S',
    image: '/hero/red-wizard.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  wizard: {
    name: 'Serilda the Blue',
    title: 'Blue Flame Wizard',
    skill: {
      title: 'Magic Arrow',
      description:
        '2 AP: magic (6+) to deal 2 damage within 2 spaces.',
      cost: 2,
    },
    skill2: {
      title: 'Arcane Insight',
      description: 'Passive: draw an extra spell when resting.',
    },
    quote: 'By the flames of knowledge!',
    movement: 3,
    hp: 5,
    maxHp: 5,
    maxAp: 6,
    ap: 6,
    defence: 3,
    strengthDice: 1,
    agilityDice: 2,
    magicDice: 3,
    icon: 'W',
    image: '/hero/blue-wizard.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  barbarian: {
    name: 'Groka Ull',
    title: 'Savage Berserker',
    skill: {
      title: 'Battle Rage',
      description:
        '2 AP: +2 on your next attack roll.',
      cost: 2,
    },
    skill2: {
      title: 'Thick Hide',
      description: 'Passive: reduce physical damage by 1.',
    },
    quote: 'CRUSH THEM ALL!',
    movement: 3,
    hp: 9,
    maxHp: 9,
    maxAp: 3,
    ap: 3,
    defence: 2,
    strengthDice: 3,
    agilityDice: 2,
    magicDice: 1,
    icon: 'B',
    image: '/hero/barbarian.png',
    weapons: [
      {
        name: 'Axe',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/weapon/viking-axe.webp',
        attackType: 'melee',
      },
    ],
  },
  rogue: {
    name: 'Lunara',
    title: 'Nightblade',
    skill: {
      title: 'Shadow Walk',
      description:
        '2 AP: agility (6+) to dash through foes and strike.',
      cost: 2,
    },
    skill2: {
      title: 'Evasion',
      description: 'Passive: first attack against you each turn has -1 to hit.',
    },
    quote: "You won't see me coming.",
    movement: 5,
    hp: 6,
    maxHp: 6,
    maxAp: 4,
    ap: 4,
    defence: 2,
    strengthDice: 2,
    agilityDice: 3,
    magicDice: 1,
    icon: 'R',
    image: '/hero/ninja.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  paladin: {
    name: 'Lady Liora',
    title: 'Battle Veteran',
    skill: {
      title: 'Divine Might',
      description:
        '2 AP: magic (4+) for +2 to next melee attack.',
      cost: 2,
    },
    skill2: {
      title: 'Aura of Courage',
      description: 'Passive: allies within 1 space gain +1 attack.',
    },
    quote: 'Light guide my hand.',
    movement: 3,
    hp: 9,
    maxHp: 9,
    maxAp: 4,
    ap: 4,
    defence: 4,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 2,
    icon: 'P',
    image: '/hero/magic-knight.png',
    weapons: [
      {
        name: 'Hammer',
        attack: 2,
        defence: 0,
        dice: 'strength',
        image: '/weapon/mjolnir.webp',
        attackType: 'melee',
      },
    ],
  },
  cleric: {
    name: 'Uliessa',
    title: 'Divine Healer',
    skill: {
      title: 'Heal',
      description:
        '2 AP: restore 4 HP to a hero up to 3 rooms away.',
      cost: 2,
    },
    skill2: {
      title: 'Blessing',
      description: 'Passive: restore 1 extra HP whenever you heal.',
    },
    quote: 'May my faith heal all wounds.',
    movement: 4,
    hp: 7,
    maxHp: 7,
    maxAp: 6,
    ap: 6,
    defence: 4,
    strengthDice: 2,
    agilityDice: 1,
    magicDice: 3,
    icon: 'C',
    image: '/hero/priestess-animate.gif',
    weapons: [
      {
        name: 'Hammer',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/weapon/earthshaker.webp',
        attackType: 'melee',
      },
    ],
  },
  ranger: {
    name: 'Wynneth Keleas',
    title: 'Swift Tracker',
    skill: {
      title: 'Stealth',
      description:
        '2 AP: move through enemies without stopping this turn.',
      cost: 2,
    },
    skill2: {
      title: 'Tracker',
      description: 'Passive: +1 range when using bows.',
    },
    quote: 'Every path leaves a trace.',
    movement: 4,
    hp: 7,
    maxHp: 7,
    maxAp: 4,
    ap: 4,
    defence: 2,
    strengthDice: 2,
    agilityDice: 3,
    magicDice: 1,
    icon: 'A',
    image: '/hero/dark-elf.png',
    weapons: [
      {
        name: 'Dagger',
        attack: 1,
        defence: 0,
        dice: 'strength',
        image: '/dagger.svg',
        attackType: 'melee',
      },
      {
        name: 'Bow',
        attack: 2,
        defence: 0,
        dice: 'agility',
        image: '/bow.svg',
        attackType: 'range',
        range: 2,
      },
    ],
  },
}

