export const HERO_TYPES = {
  knight: {
    name: 'Knight',
    skill: 'Defensive stance',
    movement: 3,
    hp: 12,
    maxHp: 12,
    maxAp: 2,
    ap: 2,
    attack: 4,
    defence: 3,
    agility: 2,
    strengthDice: 3,
    agilityDice: 1,
    magicDice: 1,
    icon: 'K',
    image: '/knight.png',
    weapons: [
      {
        name: 'Sword',
        attack: 2,
        defence: 0,
        dice: 'strength',
        image: '/sword.svg',
        attackType: 'melee',
      },
      {
        name: 'Shield',
        attack: 1,
        defence: 2,
        dice: 'strength',
        image: '/shield.svg',
        attackType: 'melee',
      },
    ],
  },
  elf: {
    name: 'Elf',
    skill: 'Forest stealth',
    movement: 4,
    hp: 8,
    maxHp: 8,
    maxAp: 3,
    ap: 3,
    attack: 3,
    defence: 1,
    agility: 4,
    strengthDice: 2,
    agilityDice: 2,
    magicDice: 2,
    icon: 'E',
    image: '/elf.svg',
    weapons: [
      {
        name: 'Bow',
        attack: 2,
        defence: 0,
        dice: 'agility',
        image: '/bow.svg',
        attackType: 'range',
      },
      {
        name: 'Dagger',
        attack: 1,
        defence: 1,
        dice: 'agility',
        image: '/dagger.svg',
        attackType: 'melee',
      },
    ],
  },
  viking: {
    name: 'Viking',
    skill: 'Berserker rage',
    movement: 3,
    hp: 10,
    maxHp: 10,
    maxAp: 2,
    ap: 2,
    attack: 5,
    defence: 2,
    agility: 2,
    strengthDice: 4,
    agilityDice: 1,
    magicDice: 0,
    icon: 'V',
    image: '/hero-viking.webp',
    weapons: [
      {
        name: 'Axe',
        attack: 3,
        defence: 0,
        dice: 'strength',
        image: '/weapon/viking-axe.webp',
        attackType: 'melee',
      },
    ],
  },
}

