const BASE_PATHS = [
  { up: true, down: true, left: true, right: true },
  { up: true, down: true, left: true, right: false },
  { up: true, down: true, left: false, right: true },
  { up: true, down: false, left: true, right: true },
  { up: false, down: true, left: true, right: true },
  { up: true, down: true, left: false, right: false },
  { up: false, down: false, left: true, right: true },
  { up: true, down: false, left: true, right: false },
  { up: true, down: false, left: false, right: true },
  { up: false, down: true, left: true, right: false },
  { up: false, down: true, left: false, right: true },
  { up: true, down: false, left: false, right: false },
  { up: false, down: true, left: false, right: false },
  { up: false, down: false, left: true, right: false },
  { up: false, down: false, left: false, right: true },
  { up: false, down: false, left: false, right: false },
]

const GOBLIN_ROOMS = Array.from({ length: 19 }, (_, i) => ({
  roomId: `Goblin Lair ${i + 1}`,
  paths: BASE_PATHS[i % BASE_PATHS.length],
  goblin: true,
}))

GOBLIN_ROOMS.push({
  roomId: 'Goblin King\'s Den',
  paths: BASE_PATHS[0],
  goblin: 'king',
})

export const ROOM_DECK = [
  { roomId: 'Chamber of Bones', paths: BASE_PATHS[0] },
  { roomId: 'Chamber of Doom', paths: BASE_PATHS[1] },
  { roomId: 'Chamber of Echoes', paths: BASE_PATHS[2] },
  { roomId: 'Chamber of Flame', paths: BASE_PATHS[3] },
  { roomId: 'Chamber of Frost', paths: BASE_PATHS[4] },
  { roomId: 'Chamber of Light', paths: BASE_PATHS[1] },
  { roomId: 'Chamber of Secrets', paths: BASE_PATHS[0] },
  { roomId: 'Chamber of Shadows', paths: BASE_PATHS[2] },
  { roomId: 'Chamber of Trials', paths: BASE_PATHS[3] },
  { roomId: 'Chamber of Whispers', paths: BASE_PATHS[4] },
  { roomId: 'Crypt of Bones', paths: BASE_PATHS[1] },
  { roomId: 'Crypt of Doom', paths: BASE_PATHS[2] },
  { roomId: 'Crypt of Echoes', paths: BASE_PATHS[3] },
  { roomId: 'Crypt of Flame', paths: BASE_PATHS[4] },
  { roomId: 'Crypt of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Crypt of Light', paths: BASE_PATHS[1] },
  { roomId: 'Crypt of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Crypt of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Crypt of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Crypt of Whispers', paths: BASE_PATHS[0] },
  { roomId: 'Hall of Bones', paths: BASE_PATHS[1] },
  { roomId: 'Hall of Doom', paths: BASE_PATHS[2] },
  { roomId: 'Hall of Echoes', paths: BASE_PATHS[3] },
  { roomId: 'Hall of Flame', paths: BASE_PATHS[4] },
  { roomId: 'Hall of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Hall of Light', paths: BASE_PATHS[1] },
  { roomId: 'Hall of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Hall of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Hall of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Hall of Whispers', paths: BASE_PATHS[0] },
  { roomId: 'Room of Bones', paths: BASE_PATHS[1] },
  { roomId: 'Room of Doom', paths: BASE_PATHS[2] },
  { roomId: 'Room of Echoes', paths: BASE_PATHS[3] },
  { roomId: 'Room of Flame', paths: BASE_PATHS[4] },
  { roomId: 'Room of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Room of Light', paths: BASE_PATHS[1] },
  { roomId: 'Room of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Room of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Room of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Room of Whispers', paths: BASE_PATHS[0] },
  { roomId: 'Sanctum of Bones', paths: BASE_PATHS[1] },
  { roomId: 'Sanctum of Doom', paths: BASE_PATHS[2] },
  { roomId: 'Sanctum of Echoes', paths: BASE_PATHS[3] },
  { roomId: 'Sanctum of Flame', paths: BASE_PATHS[4] },
  { roomId: 'Sanctum of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Sanctum of Light', paths: BASE_PATHS[1] },
  { roomId: 'Sanctum of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Sanctum of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Sanctum of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Sanctum of Whispers', paths: BASE_PATHS[0] },
  { roomId: 'Shrine of Bones', paths: BASE_PATHS[1] },
  { roomId: 'Shrine of Doom', paths: BASE_PATHS[2] },
  { roomId: 'Shrine of Echoes', paths: BASE_PATHS[3] },
  { roomId: 'Shrine of Flame', paths: BASE_PATHS[4] },
  { roomId: 'Shrine of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Shrine of Light', paths: BASE_PATHS[1] },
  { roomId: 'Shrine of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Shrine of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Shrine of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Shrine of Whispers', paths: BASE_PATHS[0] },
  { roomId: 'Vault of Bones', paths: BASE_PATHS[1] },
  { roomId: 'Vault of Doom', paths: BASE_PATHS[2] },
  { roomId: 'Vault of Echoes', paths: BASE_PATHS[3] },
  { roomId: 'Vault of Flame', paths: BASE_PATHS[4] },
  { roomId: 'Vault of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Vault of Light', paths: BASE_PATHS[1] },
  { roomId: 'Vault of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Vault of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Vault of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Vault of Whispers', paths: BASE_PATHS[0] },
  ...GOBLIN_ROOMS,
]

export function createShuffledDeck() {
  const deck = ROOM_DECK.slice()
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[deck[i], deck[j]] = [deck[j], deck[i]]
  }
  return deck
}
