const BASE_PATHS = [
  { up: true, down: true, left: true, right: true },
  { up: true, down: true, left: true, right: false },
  { up: true, down: true, left: false, right: true },
  { up: true, down: false, left: true, right: true },
  { up: false, down: true, left: true, right: true },
  { up: true, down: true, left: false, right: false },
  { up: false, down: false, left: true, right: true },
  { up: true, down: false, left: true, right: false },
  { up: true, down: false, left: false, right: true },
  { up: false, down: true, left: true, right: false },
  { up: false, down: true, left: false, right: true },
  { up: true, down: false, left: false, right: false },
  { up: false, down: true, left: false, right: false },
  { up: false, down: false, left: true, right: false },
  { up: false, down: false, left: false, right: true },
  { up: false, down: false, left: false, right: false },
]

export const ROOM_DECK = [
  { roomId: 'Chamber of Bones', paths: BASE_PATHS[0] },
  { roomId: 'Chamber of Doom', paths: BASE_PATHS[1] },
  { roomId: 'Chamber of Echoes', paths: BASE_PATHS[2] },
  { roomId: 'Chamber of Flame', paths: BASE_PATHS[3] },
  { roomId: 'Chamber of Frost', paths: BASE_PATHS[4] },
  { roomId: 'Chamber of Light', paths: BASE_PATHS[5] },
  { roomId: 'Chamber of Secrets', paths: BASE_PATHS[6] },
  { roomId: 'Chamber of Shadows', paths: BASE_PATHS[7] },
  { roomId: 'Chamber of Trials', paths: BASE_PATHS[8] },
  { roomId: 'Chamber of Whispers', paths: BASE_PATHS[9] },
  { roomId: 'Crypt of Bones', paths: BASE_PATHS[10] },
  { roomId: 'Crypt of Doom', paths: BASE_PATHS[11] },
  { roomId: 'Crypt of Echoes', paths: BASE_PATHS[12] },
  { roomId: 'Crypt of Flame', paths: BASE_PATHS[13] },
  { roomId: 'Crypt of Frost', paths: BASE_PATHS[14] },
  { roomId: 'Crypt of Light', paths: BASE_PATHS[15] },
  { roomId: 'Crypt of Secrets', paths: BASE_PATHS[16] },
  { roomId: 'Crypt of Shadows', paths: BASE_PATHS[0] },
  { roomId: 'Crypt of Trials', paths: BASE_PATHS[1] },
  { roomId: 'Crypt of Whispers', paths: BASE_PATHS[2] },
  { roomId: 'Hall of Bones', paths: BASE_PATHS[3] },
  { roomId: 'Hall of Doom', paths: BASE_PATHS[4] },
  { roomId: 'Hall of Echoes', paths: BASE_PATHS[5] },
  { roomId: 'Hall of Flame', paths: BASE_PATHS[6] },
  { roomId: 'Hall of Frost', paths: BASE_PATHS[7] },
  { roomId: 'Hall of Light', paths: BASE_PATHS[8] },
  { roomId: 'Hall of Secrets', paths: BASE_PATHS[9] },
  { roomId: 'Hall of Shadows', paths: BASE_PATHS[10] },
  { roomId: 'Hall of Trials', paths: BASE_PATHS[11] },
  { roomId: 'Hall of Whispers', paths: BASE_PATHS[12] },
  { roomId: 'Room of Bones', paths: BASE_PATHS[13] },
  { roomId: 'Room of Doom', paths: BASE_PATHS[14] },
  { roomId: 'Room of Echoes', paths: BASE_PATHS[15] },
  { roomId: 'Room of Flame', paths: BASE_PATHS[16] },
  { roomId: 'Room of Frost', paths: BASE_PATHS[0] },
  { roomId: 'Room of Light', paths: BASE_PATHS[1] },
  { roomId: 'Room of Secrets', paths: BASE_PATHS[2] },
  { roomId: 'Room of Shadows', paths: BASE_PATHS[3] },
  { roomId: 'Room of Trials', paths: BASE_PATHS[4] },
  { roomId: 'Room of Whispers', paths: BASE_PATHS[5] },
  { roomId: 'Sanctum of Bones', paths: BASE_PATHS[6] },
  { roomId: 'Sanctum of Doom', paths: BASE_PATHS[7] },
  { roomId: 'Sanctum of Echoes', paths: BASE_PATHS[8] },
  { roomId: 'Sanctum of Flame', paths: BASE_PATHS[9] },
  { roomId: 'Sanctum of Frost', paths: BASE_PATHS[10] },
  { roomId: 'Sanctum of Light', paths: BASE_PATHS[11] },
  { roomId: 'Sanctum of Secrets', paths: BASE_PATHS[12] },
  { roomId: 'Sanctum of Shadows', paths: BASE_PATHS[13] },
  { roomId: 'Sanctum of Trials', paths: BASE_PATHS[14] },
  { roomId: 'Sanctum of Whispers', paths: BASE_PATHS[15] },
  { roomId: 'Shrine of Bones', paths: BASE_PATHS[16] },
  { roomId: 'Shrine of Doom', paths: BASE_PATHS[0] },
  { roomId: 'Shrine of Echoes', paths: BASE_PATHS[1] },
  { roomId: 'Shrine of Flame', paths: BASE_PATHS[2] },
  { roomId: 'Shrine of Frost', paths: BASE_PATHS[3] },
  { roomId: 'Shrine of Light', paths: BASE_PATHS[4] },
  { roomId: 'Shrine of Secrets', paths: BASE_PATHS[5] },
  { roomId: 'Shrine of Shadows', paths: BASE_PATHS[6] },
  { roomId: 'Shrine of Trials', paths: BASE_PATHS[7] },
  { roomId: 'Shrine of Whispers', paths: BASE_PATHS[8] },
  { roomId: 'Vault of Bones', paths: BASE_PATHS[9] },
  { roomId: 'Vault of Doom', paths: BASE_PATHS[10] },
  { roomId: 'Vault of Echoes', paths: BASE_PATHS[11] },
  { roomId: 'Vault of Flame', paths: BASE_PATHS[12] },
  { roomId: 'Vault of Frost', paths: BASE_PATHS[13] },
  { roomId: 'Vault of Light', paths: BASE_PATHS[14] },
  { roomId: 'Vault of Secrets', paths: BASE_PATHS[15] },
  { roomId: 'Vault of Shadows', paths: BASE_PATHS[16] },
  { roomId: 'Vault of Trials', paths: BASE_PATHS[0] },
  { roomId: 'Vault of Whispers', paths: BASE_PATHS[1] },
]
